#!/usr/bin/env bash

# Use yt-dlp to download videos from a list of URLs from a provided file ($1)

let i=0
while IFS=$'\n' read -r line_data; do
    echo "Start ownloading: ${line_data}"
    yt-dlp "${line_data}"
    ((++i))
done < $1
